---

- name: get java version
  shell:   "java -version 2>&1"
  register: java_version_result
  changed_when: false

- name: test java version
  fail:
    msg: "this installation of tomcat requires java version {{ java_version }} or higher"
  when:  "'{{ java_version }}' not in java_version_result.stdout"

- name: get tomcat version
  shell:   "{{ catalina_home }}/bin/version.sh"
  register: tomcat_version_result
  failed_when: false
  changed_when: false

- name: check if tomcat service is running
  command: systemctl is-active tomcat
  failed_when: false
  changed_when: false
  register: tomcat_status

- name: add tomcat user
  user:
    name: "{{ tomcat_user }}"
  become: true

- name: get tomcat checksum
  set_fact:
    tomcat_checksum: "{{ tomcat_checksum_algo }}:{{ item | replace(' *' + tomcat_download_file,'') }}"
  with_url: "{{ tomcat_checksum_url }}"

- name: get tomcat
  get_url:
    url:      "{{ tomcat_url }}"
    dest:     "{{ tomcat_download_dir }}"
    checksum: "{{ tomcat_checksum }}"
  register: got_tomcat

- name: extract tomcat
  unarchive:
    src:        "{{ tomcat_download_dir }}/{{ tomcat_download_file }}"
    dest:       "{{ tomcat_install_dir }}"
    remote_src: yes
    owner:      "{{ tomcat_user }}"
  when: got_tomcat.changed

- name: symlink tomcat
  file:
    src:    "{{ tomcat_install_dir }}/{{ tomcat_dir }}"
    dest:   "{{ catalina_home }}"
    owner:  "{{ tomcat_user }}"
    state:  link

- name: set tomcat environment vars
  lineinfile:
    dest:   "/etc/profile.d/tomcat.sh"
    line:   "export CATALINA_HOME={{ catalina_home }}"
    state:  present
    create: yes

- name: set vars that follow from the value of tomcat_manager_access
  set_fact:
    access_state: "present"
  when: tomcat_manager_access
- set_fact:
    access_state: "absent"
  when: not tomcat_manager_access

- name: configure tomcat-users - roles
  lineinfile:
    dest: "{{ catalina_home }}/conf/tomcat-users.xml"
    regexp: '^<role rolename="{{ item }}" />'
    line: '<role rolename="{{ item }}" />'
    insertbefore: '</tomcat-users>'
    state: "{{ access_state }}"
  with_items: "{{ tomcat_roles }}"

- name: configure tomcat-users - users
  lineinfile:
    dest: "{{ catalina_home }}/conf/tomcat-users.xml"
    regexp: '^<user username="{{ item.username }}"'
    line: '<user username="{{ item.username }}" password="{{ item.password }}" roles="{{ item.roles }}" />'
    insertbefore: '</tomcat-users>'
    state: "{{ access_state }}"
  with_items: "{{ tomcat_users }}"

- name: configure tomcat service
  template:
    src:  "tomcat.service.j2"
    dest: "/etc/systemd/system/tomcat.service"
  notify: restart tomcat
